### ISSUE TITLE
Si structure du fichier pas correcte, le test devrait s'arrêter

### ISSUE THREAD

**Issue by MaelREBOUX** [etalab/bal#3]
J'ai modifié le nom de 2 attributs.

Pour moi : le validateur signale et doit s'arrêter, ne pas traiter les données.
Idem si aucun nom d’attributs sur la première ligne (ça arrive).

**Comment by jdesboeufs** [comment]
Un peu rigide non ?
Si l'outil permet de donner des indications tout en refusant la conformité c'est bien non ?

On peut aussi imaginer une options du genre `bal validate --strict mon-fichier.csv`
