### ISSUE TITLE
indiquer la version du format validé

### ISSUE THREAD

**Issue by juliencarnot** [etalab/bal#42]
En faisant un test en ligne, je constate que tous les champs définis par la BAL v1.2 ne sont pas reconnus et validés:

Champs non reconnus
--
lieudit_complement_nom

Il serait bon d'indiquer contre quel version du format ce validateur examine le fichier, ou de garantir sa mise à jour en même temps que chaque publication de version...

**Comment by jdesboeufs** [comment]
Bonjour,

L’adaptation du validateur pour le format BAL 1.2 est en cours.

**Comment by jdesboeufs** [comment]
Les champs de la version 1.2 sont enfin supportés.
